
services:
  api:
    container_name: businessinfo-api
    build:
      context: ./  # Usando o diretório raiz como contexto
      dockerfile: Dockerfile
    ports:
      - "5000:5002"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
